scrape_configs:
  - job_name: forums-tfa-scrape
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs:
      - targets:
          - host.docker.internal:5000
        labels:
          app: forums-tfa-local
      - targets:
          - forums-tfa-api:8080
        labels:
          app: forums-tfa-docker