scrape_configs:
  - job_name: forums-tfa-scrape
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs:
      - targets:
          - host.docker.internal:7166
        labels:
          app: forum-tfa